name: Ping Server

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Oauth Server
        run: curl --url ${{ secrets.OAUTH_SERVER_URL }}